export const imageSlider = [
  {
    id: 1,
    image: '/assets/event-1.jpg',
    title: 'Event 1',
    description: 'Description of Event 1',
  },
  {
    id: 2,
    image: '/assets/event-2.jpg',
    title: 'Event 2',
    description: 'Description of Event 2',
  },
  {
    id: 3,
    image: '/assets/event-3.jpg',
    title: 'Event 3',
    description: 'Description of Event 3',
  },
  {
    id: 4,
    image: '/assets/event-4.jpg',
    title: 'Event 4',
    description: 'Description of Event 4',
  },

  {
    id: 5,
    image: '/assets/event-5.jpg',
    title: 'Event 5',
    description: 'Description of Event 5',
  },
  {
    id: 6,
    image: '/assets/event-6.jpg',
    title: 'Event 6',
    description: 'Description of Event 6',
  },
  {
    id: 7,
    image: '/assets/event-7.jpg',
    title: 'Event 7',
    description: 'Description of Event 7',
  },
  {
    id: 8,
    image: '/assets/event-8.jpg',
    title: 'Event 8',
    description: 'Description of Event 8',
  },
  {
    id: 9,
    image: '/assets/event-9.jpg',
    title: 'Event 9',
    description: 'Description of Event 9',
  },
  {
    id: 10,
    image: '/assets/event-10.jpg',
    title: 'Event 10',
    description: 'Description of Event 10',
  },
  {
    id: 11,
    image: '/assets/event-11.jpg',
    title: 'Event 11',
    description: 'Description of Event 11',
  },
  {
    id: 12,
    image: '/assets/event-12.jpg',
    title: 'Event 12',
    description: 'Description of Event 12',
  },
  {
    id: 13,
    image: '/assets/event-13.jpg',
    title: 'Event 13',
    description: 'Description of Event 13',
  },
]

export const events = [
  {
    id: 1,
    image: '/assets/event-1.jpg',
    title: 'TechFest 2025',
    name: 'TechFest 2025',
    description:
      'Explore the latest innovations in tech, AI, and robotics with live demos and expert talks.',
    location: 'Lagos, Nigeria',
    tickets: 120,
    pricing: 'Free',
    time: '10:00 AM – 1:00 PM WAT',
    date: '5th October 2025',
  },
  {
    id: 2,
    image: '/assets/event-2.jpg',
    title: 'Lagos Art Expo',
    name: 'Lagos Art Expo',
    description:
      'A celebration of contemporary African art, featuring installations, talks, and auctions.',
    location: 'Lagos, Nigeria',
    tickets: 150,
    pricing: 'Paid',
    price: 4500,
    time: '1:00 PM – 5:00 PM WAT',
    date: '8th October 2025',
  },
  {
    id: 3,
    image: '/assets/event-3.jpg',
    title: 'Startup Ignition',
    name: 'Startup Ignition',
    description:
      'Pitch your idea, meet investors, and learn from startup founders in this high-energy event.',
    location: 'Abuja, Nigeria',
    tickets: 200,
    pricing: 'Free',
    time: '4:00 PM – 7:00 PM WAT',
    date: '12th October 2025',
  },
  {
    id: 4,
    image: '/assets/event-4.jpg',
    title: 'Taste of Naija',
    name: 'Taste of Naija',
    description:
      'Experience the richness of Nigerian cuisine with cooking demos and food tasting.',
    location: 'Port Harcourt, Nigeria',
    tickets: 180,
    pricing: 'Paid',
    price: 3000,
    time: '12:00 PM – 4:00 PM WAT',
    date: '15th October 2025',
  },
  {
    id: 5,
    image: '/assets/event-5.jpg',
    title: 'Wellness Vibes',
    name: 'Wellness Vibes',
    description:
      'A full-day health and fitness event including yoga sessions, talks, and wellness products.',
    location: 'Ibadan, Nigeria',
    tickets: 130,
    pricing: 'Free',
    time: '8:00 AM – 2:00 PM WAT',
    date: '16th October 2025',
  },
  {
    id: 6,
    image: '/assets/event-6.jpg',
    title: 'GameCon Naija',
    name: 'GameCon Naija',
    description:
      'Gaming tournament, tech booths, cosplay, and eSports finals in one exciting convention.',
    location: 'Enugu, Nigeria',
    tickets: 250,
    pricing: 'Paid',
    price: 5000,
    time: '2:00 PM – 9:00 PM WAT',
    date: '17th October 2025',
  },
  {
    id: 7,
    image: '/assets/event-7.jpg',
    title: 'Creatives Meet',
    name: 'Creatives Meet',
    description:
      'An interactive gathering of designers, writers, filmmakers, and digital artists.',
    location: 'Jos, Nigeria',
    tickets: 90,
    pricing: 'Free',
    time: '11:00 AM – 3:00 PM WAT',
    date: '18th October 2025',
  },
  {
    id: 8,
    image: '/assets/event-8.jpg',
    title: 'Fashion X',
    name: 'Fashion X',
    description:
      'A stylish showcase of next-gen Nigerian fashion brands, models, and trendsetters.',
    location: 'Abeokuta, Nigeria',
    tickets: 170,
    pricing: 'Paid',
    price: 6000,
    time: '6:00 PM – 10:00 PM WAT',
    date: '19th October 2025',
  },
  {
    id: 9,
    image: '/assets/event-9.jpg',
    title: 'Green Future Forum',
    name: 'Green Future Forum',
    description:
      'Panel discussions and workshops on sustainability, clean energy, and eco-solutions.',
    location: 'Ilorin, Nigeria',
    tickets: 110,
    pricing: 'Free',
    time: '9:00 AM – 12:00 PM WAT',
    date: '20th October 2025',
  },
  {
    id: 10,
    image: '/assets/event-10.jpg',
    title: 'Noir Film Night',
    name: 'Noir Film Night',
    description:
      'Outdoor screening of Nigerian short films with live Q&A with the directors.',
    location: 'Owerri, Nigeria',
    tickets: 140,
    pricing: 'Paid',
    price: 2500,
    time: '7:00 PM – 10:00 PM WAT',
    date: '21st October 2025',
  },
  {
    id: 11,
    image: '/assets/event-11.jpg',
    title: 'Digital Nomad Jam',
    name: 'Digital Nomad Jam',
    description:
      'Meet fellow remote workers, swap hacks, and attend workshops on freelancing and travel.',
    location: 'Uyo, Nigeria',
    tickets: 100,
    pricing: 'Free',
    time: '3:00 PM – 6:00 PM WAT',
    date: '22nd October 2025',
  },
  {
    id: 12,
    image: '/assets/event-12.jpg',
    title: 'Code & Coffee',
    name: 'Code & Coffee',
    description:
      'Morning coding sessions with devs, followed by networking over coffee and snacks.',
    location: 'Benin City, Nigeria',
    tickets: 75,
    pricing: 'Paid',
    price: 2000,
    time: '9:00 AM – 11:30 AM WAT',
    date: '23rd October 2025',
  },
  {
    id: 13,
    image: '/assets/event-13.jpg',
    title: 'Sunrise Chillout',
    name: 'Sunrise Chillout',
    description:
      'Early morning music and mindfulness experience for those who love peace and calm.',
    location: 'Makurdi, Nigeria',
    tickets: 60,
    pricing: 'Free',
    time: '4:00 AM – 6:00 AM WAT',
    date: '24th October 2025',
  },
]

export const description = [
  {
    id: 1,
    image: '/assets/event-1.jpg',
    title: 'TechFest 2025',
    name: 'TechFest 2025',
    description:
      'Explore the latest innovations in tech, AI, and robotics with live demos and expert talks.',
    location: 'Lagos, Nigeria',
    tickets: 120,

    pricing: 'Free',
    time: '10:00 AM – 1:00 PM WAT',
    date: '5th October 2025',
  },
  {
    id: 2,
    image: '/assets/event-2.jpg',
    title: 'Lagos Art Expo',
    name: 'Lagos Art Expo',
    description:
      'A celebration of contemporary African art, featuring installations, talks, and auctions.',
    location: 'Lagos, Nigeria',
    tickets: 150,
    pricing: 'Paid',
    price: 4500,
    time: '1:00 PM – 5:00 PM WAT',
    date: '8th October 2025',
  },
  {
    id: 3,
    image: '/assets/event-3.jpg',
    title: 'Startup Ignition',
    name: 'Startup Ignition',
    description:
      'Pitch your idea, meet investors, and learn from startup founders in this high-energy event.',
    location: 'Abuja, Nigeria',
    tickets: 200,
    pricing: 'Free',
    time: '4:00 PM – 7:00 PM WAT',
    date: '12th October 2025',
  },
  {
    id: 4,
    image: '/assets/event-3.jpg',
    title: 'Startup Ignition',
    name: 'Startup Ignition',
    description:
      'Pitch your idea, meet investors, and learn from startup founders in this high-energy event.',
    location: 'Abuja, Nigeria',
    tickets: 200,
    pricing: 'Free',
    time: '4:00 PM – 7:00 PM WAT',
    date: '12th October 2025',
  },
]
