export { default as Home } from './Home'
export { default as Events } from './Events'
export { default as Login } from './auth/Login'
export { default as Register } from './auth/Register'
export { default as SingleEvent } from './SingleEvent'
export { default as FavouriteEvents } from './FavouriteEvents'
export { default as NotFound } from './Error'
export { default as Profile } from './user/Profile'
